name: Lint

on: 
  # Allows you to run this workflow from another workflow
  workflow_call

# disable all the permission for the workflow
permissions: {}

jobs:
  Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    # Install skada
    - name: Checking Out Repository
      uses: actions/checkout@v5
      with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
    # Install Python & Packages
    - uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: 'pip' # caching pip dependencies
    - run: which python
    - run: pip install pre-commit
    - name: Lint with pre-commit
      run: |
        pre-commit install --install-hooks
        pre-commit run --all-files

