name: Tests minimal
run-name: Test minimal

on:   # yamllint disable-line rule:truthy
  # Allows you to run this workflow from another workflow
  workflow_call:
    inputs:
      skip_test:
        description: 'check if the tests are skipped or not'
        required: true
        type: boolean
        default: false


# disable all the permission for the workflow
permissions: {}

jobs:
  Test-minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # CHECK: Not forget to add new version of python
        python-version: ["3.13", "3.12"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    # name for files
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash -l {0}
    steps:

    # Install skada
    - name: Checking Out Repository  # yamllint disable-line rule:indentation
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    # Install Python & Packages
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # caching pip dependencies
    - run: which python
    - name: Install dependencies
      run: |
        python -m pip install --user --upgrade --progress-bar off pip
        python -m pip install --user -e .[test]
    # Run Tests
    - name: Run Tests without torch
      run: pytest skada/ --verbose --cov=skada --cov-report term
    # Codecov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        verbose: true
        env_vars: OS,PYTHON
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
